name: Run Tests in Container Action
description: Enhanced composite action for Run Tests in Container stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: docker run --rm  -v $(pwd)/test-results:/app/test-results  ${REGISTRY}/${APP_NAME}:dev  npm test -- --reporter=junit --outputFile=/app/test-results/junit.xml
    shell: bash
  - name: Publish test results (always)
    if: always()
    uses: dorny/test-reporter@v1
    with:
      name: Run Tests in Container Test Results
      path: test-results/junit.xml
      reporter: java-junit
