name: Deploy to Production Action
description: Enhanced composite action for Deploy to Production stage with comprehensive Jenkins feature support
inputs:
  k8s-production:
    description: Credential k8s-production
    required: 'false'
  deploy-env:
    description: Environment variable DEPLOY_ENV
    required: false
    default: production
runs:
  using: composite
  steps:
  - name: Run command 1
    run: helm upgrade --install ${APP_NAME}-green ./helm/${APP_NAME}  --namespace production  --create-namespace  --set image.tag=${BUILD_VERSION}  --set environment=production  --set deployment.color=green  --wait --timeout=15m
    shell: bash
  - name: Run command 2
    run: kubectl patch service ${APP_NAME} -n production  -p '{"spec":{"selector":{"color":"green"}}}'
    shell: bash
  - name: Run command 3
    run: sleep 60
    shell: bash
  - name: Run command 4
    run: helm uninstall ${APP_NAME}-blue -n production || true
    shell: bash
  - name: Run command 5
    run: helm upgrade --install ${APP_NAME}-blue ./helm/${APP_NAME}  --namespace production  --set image.tag=${BUILD_VERSION}  --set environment=production  --set deployment.color=blue  --set replicaCount=0
    shell: bash
  - name: Run Kubernetes command 1
    run: kubectl patch service ${APP_NAME} -n production \
    shell: bash
  - name: Run Kubernetes command 2
    run: kubectl patch service ${APP_NAME} -n production  -p '{"spec":{"selector":{"color":"green"}}}'
    shell: bash
  - name: Run Kubernetes command 3
    run: helm upgrade --install ${APP_NAME}-green ./helm/${APP_NAME} \
    shell: bash
  - name: Run Kubernetes command 4
    run: helm uninstall ${APP_NAME}-blue -n production || true
    shell: bash
  - name: Run Kubernetes command 5
    run: helm upgrade --install ${APP_NAME}-blue ./helm/${APP_NAME} \
    shell: bash
