apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-java-app.fullname" . }}-svc
  labels:
    {{- include "my-java-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-java-app.selectorLabels" . | nindent 4 }}