name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
  workflow_dispatch:
    inputs:
      RUN_MIGRATIONS:
        description: Run database migrations
        required: false
        default: true
        type: boolean
      PYTHON_VERSION:
        description: Python version
        required: false
        default: '3.9'
        type: choice
        options:
        - '3.9'
        - '3.10'
        - '3.11'
env:
  DJANGO_SETTINGS_MODULE: myproject.settings.test
  PYTHONPATH: .
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Setup Environment
      uses: ./.github/actions/setup-environment
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs: setup-environment
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Lint
      uses: ./.github/actions/lint
  security-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs: setup-environment
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Check
      uses: ./.github/actions/security-check
  type-check:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs: setup-environment
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Type Check
      uses: ./.github/actions/type-check
  database-setup:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    if: github.event_name == 'workflow_dispatch' && params.RUN_MIGRATIONS
    needs:
    - lint
    - security-check
    - type-check
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Database Setup
      uses: ./.github/actions/database-setup
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs:
    - type-check
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      uses: ./.github/actions/tests
    if: always() && (needs.type-check.result == 'success' || needs.type-check.result == 'failure')
    continue-on-error: true
  build-package:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs:
    - type-check
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Build Package
      uses: ./.github/actions/build-package
    if: always() && (needs.type-check.result == 'success' || needs.type-check.result == 'failure')
  docker-build:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    needs:
    - type-check
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Docker Build
      uses: ./.github/actions/docker-build
    if: always() && (needs.type-check.result == 'success' || needs.type-check.result == 'failure')
