name: Deploy Application Action
description: Enhanced composite action for Deploy Application stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: kubectl set image deployment/myapp  myapp=${DOCKER_IMAGE}:${{ github.run_number }}  -n ${NAMESPACE}
    shell: bash
  - name: Run command 2
    run: kubectl scale deployment myapp  --replicas=${REPLICAS}  -n ${NAMESPACE}
    shell: bash
  - name: Run command 3
    run: kubectl rollout status deployment/myapp  -n ${NAMESPACE}  --timeout=300s
    shell: bash
  - name: Run Kubernetes command 1
    run: kubectl set image deployment/myapp \
    shell: bash
  - name: Run Kubernetes command 2
    run: kubectl scale deployment myapp \
    shell: bash
  - name: Run Kubernetes command 3
    run: kubectl rollout status deployment/myapp \
    shell: bash
  - name: Run Kubernetes command 4
    run: kubectl set image deployment/myapp  myapp=${DOCKER_IMAGE}:${{ github.run_number }}  -n ${NAMESPACE}
    shell: bash
  - name: Run Kubernetes command 5
    run: kubectl scale deployment myapp  --replicas=${REPLICAS}  -n ${NAMESPACE}
    shell: bash
  - name: Run Kubernetes command 6
    run: kubectl rollout status deployment/myapp  -n ${NAMESPACE}  --timeout=300s
    shell: bash
