name: Unit Tests Action
description: Enhanced composite action for Unit Tests stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: mvn test
    shell: bash
  - name: publishHTML (REQUIRES MANUAL CONVERSION)
    run: "\n# MANUAL CONVERSION REQUIRED: publishHTML\n# Original Jenkins feature: publishHTML([\n                        allowMissing: false,\n                        alwaysLinkToLastB\n# Action needed: Review Jenkins documentation and implement equivalent logic\n# TODO: Implement this functionality manually\n"
    shell: bash
  - name: Publish test results (always)
    if: always()
    uses: dorny/test-reporter@v1
    with:
      name: Unit Tests Test Results
      path: target/surefire-reports/*.xml
      reporter: java-junit
