name: Security Scan Action
description: Enhanced composite action for Security Scan stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: trivy fs --format json --output trivy-results.json .
    shell: bash
