name: Type Check Action
description: Enhanced composite action for Type Check stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: npm run type-check
    shell: bash
