name: Lint Action
description: Enhanced composite action for Lint stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: npm run lint -- --format=junit --output-file=reports/eslint.xml
    shell: bash
  - name: Publish test results (always)
    if: always()
    uses: dorny/test-reporter@v1
    with:
      name: Lint Test Results
      path: reports/eslint.xml
      reporter: java-junit
