name: SonarQube SAST Action
description: Enhanced composite action for SonarQube SAST stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
runs:
  using: composite
  steps:
  - name: Run SonarQube analysis
    run: sonar-scanner  -Dsonar.projectKey=security-scan  -Dsonar.sources=.  -Dsonar.host.url=$SONAR_HOST_URL  -Dsonar.login=$SONAR_TOKEN
    shell: bash
    env:
      SONAR_TOKEN: ${{ inputs.sonar-token }}
      SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
  - name: Run command 1
    run: sonar-scanner  -Dsonar.projectKey=security-scan  -Dsonar.sources=.  -Dsonar.host.url=$SONAR_HOST_URL  -Dsonar.login=$SONAR_TOKEN
    shell: bash
