name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
  workflow_dispatch:
    inputs:
      SKIP_TESTS:
        description: Skip test execution
        required: false
        default: false
        type: boolean
      BUILD_ENV:
        description: Build environment
        required: false
        default: development
        type: choice
        options:
        - development
        - staging
        - production
env:
  REACT_APP_ENV: production
  GENERATE_SOURCEMAP: 'false'
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    container:
      image: node:18
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Install Dependencies
      uses: ./.github/actions/install-dependencies
  lint:
    runs-on: ubuntu-latest
    container:
      image: node:18
    needs: install-dependencies
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Lint
      uses: ./.github/actions/lint
  security-audit:
    runs-on: ubuntu-latest
    container:
      image: node:18
    needs: install-dependencies
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Audit
      uses: ./.github/actions/security-audit
  test:
    runs-on: ubuntu-latest
    container:
      image: node:18
    needs:
    - lint
    - security-audit
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Test
      uses: ./.github/actions/test
    continue-on-error: true
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      REACT_APP_VERSION: ${BUILD_NUMBER}
      REACT_APP_BUILD_ENV: ${params.BUILD_ENV}
    needs: test
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Build
      uses: ./.github/actions/build
      with:
        react-app-version: ${{ env.REACT_APP_VERSION }}
        react-app-build-env: ${{ env.REACT_APP_BUILD_ENV }}
  bundle-analysis:
    runs-on: ubuntu-latest
    container:
      image: node:18
    needs: build
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Bundle Analysis
      uses: ./.github/actions/bundle-analysis
    continue-on-error: true
  deploy-to-s3:
    runs-on: ubuntu-latest
    container:
      image: node:18
    if: 'true  # MANUAL CONVERSION REQUIRED: Complex when condition'
    needs: bundle-analysis
    timeout-minutes: 60
    concurrency:
      group: deployment-deploy-to-s3
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v4
    - name: Run Deploy to S3
      uses: ./.github/actions/deploy-to-s3
  pipeline-post:
    name: Pipeline Post Actions
    runs-on: ubuntu-latest
    needs:
    - install-dependencies
    - lint
    - security-audit
    - test
    - build
    - bundle-analysis
    - deploy-to-s3
    if: always()
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Publish test results (always)
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Pipeline Test Results (always)
        path: reports/eslint.xml
        reporter: java-junit
      continue-on-error: false
    container:
      image: node:18
