name: Security Scan Action
description: Enhanced composite action for Security Scan stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: trivy image --format json --output trivy-report.json ${REGISTRY}/${APP_NAME}:${{ github.run_number }}
    shell: bash
  - name: Run command 2
    run: trivy image --exit-code 1 --severity HIGH,CRITICAL ${REGISTRY}/${APP_NAME}:${{ github.run_number }}
    shell: bash
