name: Deploy to Staging Action
description: Enhanced composite action for Deploy to Staging stage with comprehensive Jenkins feature support
inputs:
  k8s-staging:
    description: Credential k8s-staging
    required: 'false'
  deploy-env:
    description: Environment variable DEPLOY_ENV
    required: false
    default: staging
runs:
  using: composite
  steps:
  - name: Run command 1
    run: helm upgrade --install ${APP_NAME} ./helm/${APP_NAME}  --namespace staging  --create-namespace  --set image.tag=${BUILD_VERSION}  --set environment=staging  --wait --timeout=10m
    shell: bash
  - name: Run command 2
    run: sleep 30
    shell: bash
  - name: Run command 3
    run: kubectl get pods -n staging
    shell: bash
  - name: Run command 4
    run: kubectl wait --for=condition=ready pod -l app=${APP_NAME} -n staging --timeout=300s
    shell: bash
  - name: Run Kubernetes command 1
    run: kubectl get pods -n staging
    shell: bash
  - name: Run Kubernetes command 2
    run: kubectl wait --for=condition=ready pod -l app=${APP_NAME} -n staging --timeout=300s
    shell: bash
  - name: Run Kubernetes command 3
    run: kubectl get pods -n staging
    shell: bash
  - name: Run Kubernetes command 4
    run: kubectl wait --for=condition=ready pod -l app=${APP_NAME} -n staging --timeout=300s
    shell: bash
  - name: Run Kubernetes command 5
    run: helm upgrade --install ${APP_NAME} ./helm/${APP_NAME} \
    shell: bash
