name: Deploy to Kubernetes Action
description: Enhanced composite action for Deploy to Kubernetes stage with comprehensive Jenkins feature support
inputs:
  image-tag:
    description: Parameter IMAGE_TAG
    required: true
  environment:
    description: Parameter ENVIRONMENT
    required: true
runs:
  using: composite
  steps:
  - name: Run command 1
    run: helm upgrade --install myapp ${HELM_CHART_PATH}  --namespace ${NAMESPACE}  --create-namespace  --values ${HELM_CHART_PATH}/${valuesFile}  --set image.tag=${{ inputs.IMAGE_TAG }}  --wait --timeout=10m
    shell: bash
  - name: Run Kubernetes command 1
    run: helm upgrade --install myapp ${HELM_CHART_PATH} \
    shell: bash
  - name: Script block 1 (REQUIRES MANUAL CONVERSION)
    run: "\n# MANUAL CONVERSION REQUIRED: Complex script block\n# Original Jenkins feature: def valuesFile = \"values-${params.ENVIRONMENT}.yaml\"\n                    sh \"\"\"\n                        helm upgrade --install myapp ${HELM_CHART_PATH} \\\n                            --namespace ${NAME\n# Action needed: Review Jenkins documentation and implement equivalent logic\n# TODO: Implement this functionality manually\n"
    shell: bash
