name: Database Migration Action
description: Enhanced composite action for Database Migration stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: kubectl create job migration-${{ github.run_number }}  --from=cronjob/db-migration  --namespace=${NAMESPACE}
    shell: bash
  - name: Run command 2
    run: kubectl wait --for=condition=complete job/migration-${{ github.run_number }}  --timeout=300s --namespace=${NAMESPACE}
    shell: bash
  - name: Run Kubernetes command 1
    run: kubectl create job migration-${{ github.run_number }} \
    shell: bash
  - name: Run Kubernetes command 2
    run: kubectl wait --for=condition=complete job/migration-${{ github.run_number }} \
    shell: bash
  - name: Run Kubernetes command 3
    run: kubectl create job migration-${{ github.run_number }}  --from=cronjob/db-migration  --namespace=${NAMESPACE}
    shell: bash
  - name: Run Kubernetes command 4
    run: kubectl wait --for=condition=complete job/migration-${{ github.run_number }}  --timeout=300s --namespace=${NAMESPACE}
    shell: bash
