name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
  workflow_dispatch:
    inputs:
      FAIL_ON_HIGH:
        description: Fail build on high severity issues
        required: false
        default: true
        type: boolean
      SCAN_TYPE:
        description: Type of security scan
        required: false
        default: full
        type: choice
        options:
        - full
        - incremental
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkout
      uses: ./.github/actions/checkout
  sonarqube-sast:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run SonarQube SAST
      uses: ./.github/actions/sonarqube-sast
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
  semgrep-sast:
    runs-on: ubuntu-latest
    needs: sonarqube-sast
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Semgrep SAST
      uses: ./.github/actions/semgrep-sast
  codeql-analysis:
    runs-on: ubuntu-latest
    needs: semgrep-sast
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run CodeQL Analysis
      uses: ./.github/actions/codeql-analysis
  checkmarx-sast:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && params.SCAN_TYPE == 'full'
    needs: codeql-analysis
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkmarx SAST
      uses: ./.github/actions/checkmarx-sast
  dependency-check:
    runs-on: ubuntu-latest
    needs:
    - codeql-analysis
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Dependency Check
      uses: ./.github/actions/dependency-check
    if: always() && (needs.codeql-analysis.result == 'success' || needs.codeql-analysis.result == 'failure')
  security-report:
    runs-on: ubuntu-latest
    needs:
    - codeql-analysis
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Report
      uses: ./.github/actions/security-report
    if: always() && (needs.codeql-analysis.result == 'success' || needs.codeql-analysis.result == 'failure')
    continue-on-error: true
