name: Build Development Image Action
description: Enhanced composite action for Build Development Image stage with comprehensive Jenkins feature support
inputs:
  registry:
    description: Docker registry URL
    required: false
    default: docker.io
  image-name:
    description: Docker image name
    required: true
  build-tag:
    description: Docker build tag
    required: false
    default: latest
runs:
  using: composite
  steps:
  - name: Build Docker image
    run: docker build -t ${REGISTRY}/${APP_NAME}:dev .
    shell: bash
  - name: Build Docker image
    run: docker build -t ${REGISTRY}/${APP_NAME}:dev .
    shell: bash
