name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
  workflow_dispatch:
    inputs:
      MATRIX_TYPE:
        description: Matrix build type
        required: false
        default: full
        type: choice
        options:
        - full
        - minimal
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  matrix-build:
    runs-on:
    - self-hosted
    - ${OS}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Matrix Build
      uses: ./.github/actions/matrix-build
  collect-results:
    runs-on:
    - self-hosted
    - ${OS}
    needs: matrix-build
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Collect Results
      uses: ./.github/actions/collect-results
