name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  checkout:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkout
      uses: ./.github/actions/checkout
  build:
    runs-on: ubuntu-latest
    needs: checkout
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Build
      uses: ./.github/actions/build
  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Test
      uses: ./.github/actions/test
  package:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Package
      uses: ./.github/actions/package
  pipeline-post:
    name: Pipeline Post Actions
    runs-on: ubuntu-latest
    needs:
    - checkout
    - build
    - test
    - package
    if: always()
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Publish test results (always)
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Pipeline Test Results (always)
        path: target/surefire-reports/*.xml
        reporter: java-junit
      continue-on-error: false
