name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
  app-name:
    description: Parameter APP_NAME
    required: true
runs:
  using: composite
  steps:
  - name: Run SonarQube analysis
    run: mvn sonar:sonar  -Dsonar.projectKey=${{ inputs.APP_NAME }}  -Dsonar.projectName=${{ inputs.APP_NAME }}  -Dsonar.projectVersion=${{ github.sha }}
    shell: bash
    env:
      SONAR_TOKEN: ${{ inputs.sonar-token }}
      SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
