name: Smoke Tests Action
description: Enhanced composite action for Smoke Tests stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: kubectl run smoke-test-${{ github.run_number }} --rm -i --restart=Never  --image=curlimages/curl  -- sh -c "
    shell: bash
  - name: Run command 2
    run: curl -f http://${APP_NAME}-${NEW_COLOR}.${NAMESPACE}.svc.cluster.local:8080/api/version
    shell: bash
  - name: Run command 3
    run: curl -f http://${APP_NAME}-${NEW_COLOR}.${NAMESPACE}.svc.cluster.local:8080/api/status
    shell: bash
  - name: Run command 4
    run: '"'
    shell: bash
  - name: Run Kubernetes command 1
    run: kubectl run smoke-test-${{ github.run_number }} --rm -i --restart=Never \
    shell: bash
  - name: Run Kubernetes command 2
    run: kubectl run smoke-test-${{ github.run_number }} --rm -i --restart=Never  --image=curlimages/curl  -- sh -c "
    shell: bash
