replicaCount: 1

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Dev environment specific configurations
service:
  type: NodePort

# Enable debug logging in dev
logging:
  level: DEBUG