replicaCount: 2

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Staging environment specific configurations
service:
  type: ClusterIP

# Enable more monitoring in staging
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus