name: CI Pipeline
'on':
  push:
    branches:
    - master
    - main
    - develop
  pull_request:
    branches:
    - master
    - main
    - develop
env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'
permissions:
  contents: read
  actions: read
  security-events: write
  deployments: write
  checks: write
jobs:
  checkout:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Checkout
      uses: ./.github/actions/checkout
  frontend-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    needs: checkout
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Frontend Tests
      uses: ./.github/actions/frontend-tests
    continue-on-error: true
  backend-tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    needs: checkout
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Backend Tests
      uses: ./.github/actions/backend-tests
  security-scan:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    needs: checkout
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Security Scan
      uses: ./.github/actions/security-scan
  integration-tests:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    needs:
    - frontend-tests
    - backend-tests
    - security-scan
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Run Integration Tests
      uses: ./.github/actions/integration-tests
  pipeline-post:
    name: Pipeline Post Actions
    runs-on: ubuntu-latest
    needs:
    - checkout
    - frontend-tests
    - backend-tests
    - security-scan
    - integration-tests
    if: always()
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Publish HTML (always) - MANUAL CONVERSION REQUIRED
      if: always()
      run: "\n# MANUAL CONVERSION REQUIRED: PublishHTML Plugin\n# Original Jenkins feature: publishHTML([\n                                allowMissing: false,\n                                alwaysLinkToLastBuild: true,\n                                keepAll: true,\n                                reportDir: 'coverage',\n                                reportFiles: 'index.html',\n                                reportName: 'Frontend Coverage Report'\n                            ])\n# Action needed: Review Jenkins documentation and implement equivalent logic\n# TODO: Implement this functionality manually\n"
      shell: bash
    container:
      image: node:18-alpine
