name: Install Dependencies Action
description: Enhanced composite action for Install Dependencies stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Run command 1
    run: npm ci
    shell: bash
  - name: Run command 2
    run: npm ls --depth=0
    shell: bash
